// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(SightseeingContext))]
    [Migration("20240110191528_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Core.Entities.Mountain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateOfVisit")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ElevationGainInMeters")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EndPlace")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MountainsRangeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("StartPlace")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TripLenghtInKm")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TripTimeHours")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TripTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Visited")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VoivodeshipId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MountainsRangeId");

                    b.HasIndex("VoivodeshipId");

                    b.ToTable("Mountains");
                });

            modelBuilder.Entity("Core.Entities.MountainsRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MountainsRanges");
                });

            modelBuilder.Entity("Core.Entities.Voivodeship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Voivodeships");
                });

            modelBuilder.Entity("Core.Entities.Mountain", b =>
                {
                    b.HasOne("Core.Entities.MountainsRange", "MountainsRange")
                        .WithMany()
                        .HasForeignKey("MountainsRangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Voivodeship", "Voivodeship")
                        .WithMany()
                        .HasForeignKey("VoivodeshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MountainsRange");

                    b.Navigation("Voivodeship");
                });
#pragma warning restore 612, 618
        }
    }
}
